spring:
  profiles:
    group:
      "local": "localdb,common"
      "live": "livedb,common"

---

spring:
  config:
    activate:
      on-profile: "localdb"
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
        jdbc-url: jdbc:h2:mem:testdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---

spring:
  config:
    activate:
      on-profile: "livedb"
  datasource:
    username: root
    password: pass
    url: jdbc:mariadb://localhost:3306/bigescape?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver

---

spring:
  config:
    activate:
      on-profile: "common"

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 8099