spring:
  profiles:
    group:
      "dev": "localdb,common"
      "live": "livedb,common"

---

spring:
  config:
    activate:
      on-profile: "localdb"
  datasource:
    username: root
    password: pass
    url: jdbc:mariadb://localhost:3306/bigescape?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

---

spring:
  config:
    activate:
      on-profile: "livedb"
  datasource:
    username: root
    password: pass
    url: jdbc:mariadb://localhost:3306/bigescape?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver

---

spring:
  config:
    activate:
      on-profile: "common"

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 8099